### ISSUE TITLE
Internal server error 500

### ISSUE THREAD

**Issue by pmwoodward3** [Prajithp/letsencrypt-cpanel#1]
Just ran into this, after installing the plugin, when I visit its plugin page I see this:

Internal Server Error

500

No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.

Any idea whats happening? The install script didnt have any errors and python 2.7 is installed correctly.

**Comment by pmwoodward3** [comment]
error log output when viewing the plugin page:

Can't locate Cpanel/PublicAPI.pm in @INC (@INC contains: /usr/local/cpanel /usr/local/cpanel/3rdparty/perl/514/lib64/perl5/cpanel_lib/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/514/lib64/perl5/cpanel_lib /usr/local/cpanel/3rdparty/perl/514/lib64/perl5/5.14.4/x86_64-linux-64int /usr/local/cpanel/3rdparty/perl/514/lib64/perl5/5.14.4 /opt/cpanel/perl5/514/site_lib/x86_64-linux-64int /opt/cpanel/perl5/514/site_lib .) at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 5.
BEGIN failed--compilation aborted at /usr/local/cpanel/Cpanel/LetsEncrypt.pm line 5.
Compilation failed in require at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 6.
BEGIN failed--compilation aborted at /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 6.
[2016-01-16 13:11:22 -0500] info [cpsrvd] Internal Server Error: "GET /cpsess7744483718/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.

**Comment by Prajithp** [comment]
Yes, In 11.54, cPanel has changed their public api module to cPanel::PublicAPI.
This has been fixed and updated the repository. Kindly uninstall the current version and install it again.

# Uninstall Command
```
rm -rf /usr/local/cpanel/Cpanel/LetsEncrypt.pm /usr/local/letsencrypt/ /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/
```
Please test it out and let me know.

**Comment by pmwoodward3** [comment]
Thanks! that got the plugin page fixed, but now when I click "install letsencrypt ssl cert" the popup has a dropdown box with no options when I click on it.

Also it would be awesome if there was a "get ssl certs for all accounts" button or function.

Thanks again, really great work :)

**Comment by Prajithp** [comment]
Could you please send me a screenshot of the error message to prajithpalakkuda@gmail.com? 

Regarding new feature "get ssl certs for all accounts",  Request rate limits are currently in place for the Let’s Encrypt service, so if we request for multiple ssl certificate within minutes, they may block the server ip. Anyway I'm adding this as a feature request and will work on it.
