### ISSUE TITLE
Issue with issuing SSL cert

### ISSUE THREAD

**Issue by arshem** [Prajithp/letsencrypt-cpanel#101]
Error occurred: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: mail.arshem.com, Type: urn:acme:error:unauthorized

I get this when trying to install an SSL cert. Ideas?

**Comment by WilliamIsted** [comment]
Is the DNS serving records for that address?

**Comment by arshem** [comment]
It uses CNAME for that address, no A record for mail

**Comment by WilliamIsted** [comment]
What is the CNAME set to?

**Comment by arshem** [comment]
arshem.com.

**Comment by WilliamIsted** [comment]
I'm not seeing any DNS records for that domain at all

**Comment by arshem** [comment]
http://mxtoolbox.com/SuperTool.aspx?action=cname%3amail.arshem.com&run=toolpage#

**Comment by arshem** [comment]
I found the issue: My firewall wasn't allowing DNS lookups, thus the call was failing. Sorry William!

**Comment by WilliamIsted** [comment]
No problem, it did throw me off that mxtoolbox was able to do the lookup.
