### ISSUE TITLE
install certificate on whm/cpanel/webmail services

### ISSUE THREAD

**Issue by ssteeltm** [Prajithp/letsencrypt-cpanel#11]
Hello, it worked fine on my hosted domains! But I was wondering if there is anyway to install these certificates on WHM service (2083, 2087, webmail,cpanel, etc)?

Thank you!

**Comment by ashworthconsulting** [comment]
Yes, please. I'm wondering the same thing.

**Comment by pgasiorowski** [comment]
Same here, adding Exim to the mix of services.

**Comment by hedqvist** [comment]
Would be great! I can donate a few beers for this!

**Comment by Prajithp** [comment]
Started working on it :)

**Comment by ssteeltm** [comment]
Hello Prajith,
Using pure letsencrypt plugin I was able to generate one certificate with
these domains included: www.domain.com , domain.com , mail.domain.com ,
ftp.domain.com , whm.domain.com , server.domain.com .

Synce letsencrypt uses acme to validate, I wasnt able to generate for these
address: webmail.domain.com and cpanel.domain.com. I didnt find where is
webroot for these.

Webroot for whm:
/usr/local/cpanel/whostmgr/docroot/

Webroot for mail, server, ftp:

## /usr/local/apache/htdocs/

After we make a certificate with all these subdomains san included, I guess
we only have to assign this certificate To run under services mail(enable
SIN) ftp whm etc... ( found one panel on whm to do this).

Hope this info can help you.
Em 20/02/2016 04:37, "Prajith" notifications@github.com escreveu:

**Comment by BeZazz** [comment]
May be of some help
https://forums.cpanel.net/threads/cpanel-ssl-certs-lets-encrypt.522041/#post-2121701

**Comment by Prajithp** [comment]
Thank you for the link :) Actually this can be done using WHM API 1 Functions - install_service_ssl_certificate https://documentation.cpanel.net/display/SDK/WHM+API+1+Functions+-+install_service_ssl_certificate

 I will be able to release this by tomorrow evening :+1:

**Comment by hedqvist** [comment]
👍🏻
Very nice

**Comment by Prajithp** [comment]
This has been merged into the main branch :+1:  Please try this out and let me know.

**Comment by BeZazz** [comment]
I tried this on the only server I had that didn't have a Comodo cert on.

I do not know if it is repeatable or not but I had to restart the cPanel service for the cert to take affect.

**Comment by Prajithp** [comment]
Yes, you have to restart cpsrvd service to take affect the changes. I clearly mentioned it in the message after the installation. Please try this out and give me a feedback, so that I can improve this.

**Comment by hedqvist** [comment]
It should be enough to Run The upgrade.sh now right?

**Comment by Prajithp** [comment]
Yes, simply clone it and run upgrade.sh :)

**Comment by ashworthconsulting** [comment]
Or use `cd ~/letsencrypt-cpanel` (or wherever you originally cloned it) and then `git pull; ./upgrade.sh;`

**Comment by ashworthconsulting** [comment]
@Prajithp 

Any reason why we don't execute `service cpanel restart` as part of the script? Just curious. I'm all about automation and easier processes. If you feel it's best to have it separated out as a manual action, I'm okay with that as well.

**Comment by BeZazz** [comment]
Sorry I obviously didn't pay attention.

**Comment by Prajithp** [comment]
@ashworthconsulting, Actually in my test server I had some issues while restarting cpsrvd, that's why I didn't add that option. Will test this on different servers and update here.

**Comment by hedqvist** [comment]
ran the upgrade.sh without any issues, tried to install certificates on all the services.

> Internal Server Error
> 500
> No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.

usr/local/cpanel/logs/error_log

> [2015-10-29 09:58:04 -0400] warn [updatenow] Cannot update cache file: /var/cpanel/cpanel.config.cache No such file or directory at ./updatenow.static line 4886, <GEN16> line 1.
>         Cpanel::Debug::log_warn('Cannot update cache file: /var/cpanel/cpanel.config.cache No ...') called at ./updatenow.static line 8993
>         Cpanel::Config::CpConfGuard::_update_cache('Cpanel::Config::CpConfGuard=HASH(0x3673c88)') called at ./updatenow.static line 9033

**Comment by Prajithp** [comment]
Could you please send the complete log file 'usr/local/cpanel/logs/error_log' to prajithpalakkuda@gmail.com? I could not find anything in the above log result.

**Comment by hedqvist** [comment]
> Could you please send the complete log file 'usr/local/cpanel/logs/error_log' to prajithpalakkuda@gmail.com? I could not find anything in the above log result.

Sent!

**Comment by hedqvist** [comment]
any news on the log file?

**Comment by hedqvist** [comment]
Tried to reinstall... no success..

**Comment by Erreu** [comment]
Hi ssteeltm,

Could you share the command line that you used to create the additional names (mail.domain.com, ftp.domain.com, whm.domain.com). Did you use whmap1?

**Comment by ssteeltm** [comment]
Erreu, I've used official letsencrypt plugin.
./letsencrypt/letsencrypt-auto certonly --webroot 
    -w /usr/local/apache/htdocs/ -d ftp.domain.com -d server02.domain.com -d mail.domain.com 
    -w /usr/local/cpanel/whostmgr/docroot/ -d whm.domain.com
    -w /home/domain/public_html/ -d www.domain.com -d domain.com

The Official Letsencrypt plugin supports multiple webroots  and  subdomains in one certificate.

When I oppened this thread, I wanted to letsencrypt-cpanel to do the same, with multiple webroot support.

**Comment by Erreu** [comment]
ssteeltm, ah, of course. I misread your post and thought you were accessing Prajith's plugin directly.

**Comment by ssteeltm** [comment]
Prajith already made a Great Job!
But if had this support would be awesome =]
Generate one certificate with all this subdomais as default, with corresponding webroot, and also the function he already made to install a certificate on whm services.

**Comment by Prajithp** [comment]
@ssteeltm Can you please confirm, how you want to generate the cert?

**Comment by ssteeltm** [comment]
@Prajithp, Actually letsencrypt-cpanel generate certificate with one "webroot".
So what I need is this certificate to have more subdomains, with other webroot,
On whm we have these subdomains for each domain account as default:
whm.domain.com
cpanel.domain.com
webmail.domain.com
 ftp.domain.com
mail.domain.com
whm.domain.com

Actually letsencrypt-cpanel does create one certificate with one webroot.
Using official letsencrypt plugin, they made support to generate one certificate with multiple webroot. So I can have one cert. with all these subdomains included.

**Comment by Prajithp** [comment]
OK I understood. But, could u plz share your apache conf with me? because in my server, if I access cpanel.domain.com it is keep redirecting to cpanel.domain.com:2083

**Comment by ssteeltm** [comment]
I'll send on prajithpalakkuda@gmail.com.
I'm using:
CENTOS 6.7 x86_64 kvm –  WHM 54.0 (build 18)  
On mine, cpanel/webmail/whm opens ok on both ports 2083 or 80/443.

**Comment by Prajithp** [comment]
@ssteeltm I can see that cpanel.\* whm.\* all mentioned subdomains are using default cPanel/WHM certificate, so i'm not sure how did you install the certificate for these subdomains. 

Anyway, will look into this issue and update you.

```
    ServerAlias cpanel.* whm.* webmail.* webdisk.* cpcalendars.* cpcontacts.* autodiscover.* autoconfig.*

    DocumentRoot /usr/local/apache/htdocs
    ServerAdmin cassiano@newgate.inf.br
    <IfModule mod_suphp.c>
        suPHP_UserGroup nobody nobody
    </IfModule>
    <IfModule mod_security2.c>
        SecRuleEngine Off
    </IfModule>
    RewriteEngine On
    <IfModule mod_ssl.c>
        SSLEngine on
        SSLProxyEngine On
        SSLProxyVerify none
        # Setting to Off for backwards-compatibility
        # Read for more info: http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslproxycheckpeercn
        SSLProxyCheckPeerCN Off
        SSLProxyCheckPeerName Off
        SSLProxyCheckPeerExpire Off
        SSLCertificateFile /var/cpanel/ssl/cpanel/mycpanel.pem
        SSLCertificateKeyFile /var/cpanel/ssl/cpanel/mycpanel.pem
        SSLCertificateChainFile /var/cpanel/ssl/cpanel/mycpanel.pem
```

**Comment by ssteeltm** [comment]
I've just generated the certificate, didnt install on service yet.
I can enable so you can see

On Fri, Mar 4, 2016 at 12:39 AM, Prajith notifications@github.com wrote:

> @ssteeltm https://github.com/ssteeltm I can see that cpanel.\* whm.\* all
> mentioned subdomains are using default cPanel/WHM certificate, so i'm not
> sure how did you install the certificate for these subdomains.
> 
> Anyway, will look into this issue and update you.
> 
> ```
> ServerAlias cpanel.* whm.* webmail.* webdisk.* cpcalendars.* cpcontacts.* autodiscover.* autoconfig.*
> 
> DocumentRoot /usr/local/apache/htdocs
> ServerAdmin cassiano@newgate.inf.br
> <IfModule mod_suphp.c>
>     suPHP_UserGroup nobody nobody
> </IfModule>
> <IfModule mod_security2.c>
>     SecRuleEngine Off
> </IfModule>
> RewriteEngine On
> <IfModule mod_ssl.c>
>     SSLEngine on
>     SSLProxyEngine On
>     SSLProxyVerify none
>     # Setting to Off for backwards-compatibility
>     # Read for more info: http://httpd.apache.org/docs/2.4/mod/mod_ssl.html#sslproxycheckpeercn
>     SSLProxyCheckPeerCN Off
>     SSLProxyCheckPeerName Off
>     SSLProxyCheckPeerExpire Off
>     SSLCertificateFile /var/cpanel/ssl/cpanel/mycpanel.pem
>     SSLCertificateKeyFile /var/cpanel/ssl/cpanel/mycpanel.pem
>     SSLCertificateChainFile /var/cpanel/ssl/cpanel/mycpanel.pem
> ```
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Prajithp/letsencrypt-cpanel/issues/11#issuecomment-192082428
> .

## 

---

Hugo Sampaio
Email: ssteeltm@gmail.com

**Comment by Prajithp** [comment]
Yes, please install and let me know.

**Comment by ssteeltm** [comment]
@Prajithp, I enabled the certificate with multiple webroot.
This enabled cert. was made to these domains: domain.com www.domain.com ftp.domain.com and mail.domain.com.

Guess will not be possible with subdomain whm.\* / cpanel\* / webmail\* , It didnt workout because of the login page protection wich acts under they webroot (so when letsencrypt server try to reach these on ./well-known/acme-challenge/.... can't reach)

**Comment by Erreu** [comment]
@ssteeltm Just an FYI, cpanel has a switch "Proxy Subdomains" in Tweak Settings to enable using the client certificate on the service's subdomains (cpanel,whm,webdisk, and webmail). I have NOT been able to get this to work on my test server. I may need to open a Cpanel support ticket to find out why. It is documented here: https://documentation.cpanel.net/display/CKB/Proxy+Subdomains+Use+the+cPanel+Service+SSL

**Comment by mattheobjornson** [comment]
> Guess will not be possible with subdomain whm.\* / cpanel\* / webmail\* , It didnt workout because of the login page protection wich acts under they webroot (so when letsencrypt server try to reach these on ./well-known/acme-challenge/.... can't reach)

Actually, I think it would be possible using dns-01 challenge combined with some DNS zone modification API calls, instead of file-based http-01 challenge.

**Comment by BeZazz** [comment]
https://blog.cpanel.com/the-cpanel-market-provider-and-free-hostname-ssls/

**Comment by Prajithp** [comment]
@BeZazz I have tried that, but seems it is still in beta

**Comment by hbouma** [comment]
While its great that your plugin can now install certs for the cPanel services, could you not have it automatically do it? Your plugin has happily overwritten my paid for valid certs with Let's Encrypt certs. I was not happy to see that.

**Comment by hostfusion** [comment]
Hello,

the plugin have overwritten the COMODO ssl provided by cPanel for WHM services with Let´s encrypt SSL, the cPanel SSL was for one year, how to revert this issue ?

Regards

PS

**Comment by Prajithp** [comment]
@hostfusion @hbouma  The plugin won't overwrite your existing certificate automatically, But It could happen if you click on the "Install letsencrypt on whm services" and then click the submit button.

**Comment by hostfusion** [comment]
Hello Prajithp, 

thanks for reply, i have tested in 4 different servers, none have pressed the button to install let's encrypt in whm, however ssl cpanel all have been overwritten by  let's encrypt certificates.

Regards

PS

**Comment by hostfusion** [comment]
Hi again,

i have revert and issue again the cPanel SSL from Manage Service SSL Certificates, i hope this help other people with same issue.

Regards

PS

**Comment by hbouma** [comment]
I didn't click on the "install letsencrypt on whm services" button either and it replaced both my servers' cpanel ssl certificates as well.

**Comment by Prajithp** [comment]
@hbouma @hostfusion There was a bug in the Service.pm module which was causing this issue. This has been fixed in the last merge.

**Comment by hostfusion** [comment]
Hello @Prajithp ,

thanks a lot for you time revising and fixing this issue

Regards

PS

**Comment by hostfusion** [comment]
Hello @Prajithp,

i reopen this ticket because the upgrade on the file lib/Cpanel (fix for default ssl certificate overwrite) don´t fix the issue, still overwrite the default cPanel ssl certificate every day with Let´s encrypt certificate.

Would you please verify this issue ?

Regards

PS

**Comment by JialuZhang** [comment]
@Prajithp 

In your posted configuration,
```
RewriteEngine On
```
the line "RewriteEngine On“ is a silent misconfiguration. This means adding it to your system will not change any system behavior.
"RewriteEngine On" is introduced by Apache to explicitly enable all "RewriteRule" and "RewriteCond".
That is to say, unless you include multiple "RewriteRule" and "RewriteCond" parameters in your configuration, then leaving off "RewriteEngine" is a better choice.

More importantly, the default value of “RewriteEngine" is already an "off", so from a security side, deleting “RewriteEngine On” would be ideal.

The related Apache source code snippet:
```
run_rewritemap_programs(server_rec *s , apr_pool_t *p){
if (conf->state == ENGINE_DISABLED) { // usage of "RewriteEngine"
  return APR_SUCCESS; // early return
rewritemap_program(...); // usage of "RewriteRule" 
}
```
