### ISSUE TITLE
malformed JSON string

### ISSUE THREAD

**Issue by ashworthconsulting** [Prajithp/letsencrypt-cpanel#12]
Getting this error when attempting to install SSL on a domain for the first time.

> malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "Net::SSLeay 1.49 mus...") at /usr/local/share/perl5/Protocol/ACME.pm line 1028.

**Comment by ashworthconsulting** [comment]
Gotten this error on two different cPanel servers now. Each in different data centers.

Thank you for looking into this.

**Comment by Prajithp** [comment]
Hi,

This can be happen if you enabled  any security settings in whm, so please
check the same and let me know.

Also, if you can give teamviewer or any other type of access to server, I
can help you further on this.

My personal mail id: prajithpalakkuda@gmail.com

**Comment by ashworthconsulting** [comment]
Just emailed you some info. Thanks!

**Comment by Prajithp** [comment]
Thank you for the access, managed to fix this issue by updating Net::SSLeay module to latest version

**Comment by ashworthconsulting** [comment]
Yep, and it's working. Thanks again!
