### ISSUE TITLE
"Renew letsencrypt SSL Cert" button

### ISSUE THREAD

**Issue by ashworthconsulting** [Prajithp/letsencrypt-cpanel#14]
Good morning. This is non-urgent. Just curiosity.

The "Renew letsencrypt SSL Cert"...what's it for? Certs renew automatically, so I'm just curious what it's for. What its function is. Thanks!!

**Comment by Prajithp** [comment]
Yes, previously there was no cron setup for renewing the certificate. I will remove the button from whm interface. Thanks for the heads up :)
