### ISSUE TITLE
Request: Cpanel User Add ssl

### ISSUE THREAD

**Issue by dochardi** [Prajithp/letsencrypt-cpanel#17]
Hello Maby you can Add are way that costumers can add ssl to ther owner domain so that the admins not need to do it or a post wwwaccountcreate so that all acount get ssl automaticly??

that would be great why atm us tech need to do it for all user

besth wish

kai

**Comment by Prajithp** [comment]
Yes, already started working on this :+1:

**Comment by will-ashworth** [comment]
:+1:

**Comment by Prajithp** [comment]
This has been merged into the main branch, please test it out and let me know :+1:

**Comment by will-ashworth** [comment]
@Prajithp  I just did a `git pull` and then `./upgrade.sh`

The colors of the buttons in WHM look different now, and I'm on the newest version. But not seeing anything in cPanel for users to do themselves. Where should I be looking inside cPanel?

**Comment by dochardi** [comment]
@Prajithp i have just try it on all us cpanel server and its work fine 

@will-ashworth maby you need to give the client /user the right do use it and you finde it untder security/ssl ther you see are icon wo say Let's Encrypte

**Comment by Prajithp** [comment]
@will-ashworth Could you please check the feature manager and see whether it is enabled or not?
@dochardi Thank u for the confirmation.

**Comment by dochardi** [comment]
Maby you can do to enable certs by default on all domains and all subdomains without the customer needing to do anything, so the ability to 1- mass enable and 2- enable by default on new domains would be great. Of course letsencrypt ratelimits would need to be managed when doing something like this

**Comment by Prajithp** [comment]
This will be open till letsencript remove the ratelimit feature.

**Comment by AbdelElrafa** [comment]
How can I disable this? I don't want users to be able to do it, just the root user in WHM to do it?

**Comment by Prajithp** [comment]
@CapnKlutch You can disable this from the WHM feature manager.
