### ISSUE TITLE
Error on renew

### ISSUE THREAD

**Issue by macklus** [Prajithp/letsencrypt-cpanel#19]
Hi:

When i run renew_letsencrypt_ssk.pl as root, it dies with message:

Failed to renew SSL certificate for hostname : Died at /usr/local/cpanel/Cpanel/LetsEncrypt/Service.pm line 147

who can this problem be resolv ?

thanks in advance

**Comment by Prajithp** [comment]
This has been fixed in the last merge, please update your code and let me know.
