### ISSUE TITLE
Error adding cert for subdomain.example.com

### ISSUE THREAD

**Issue by cjbooth22** [Prajithp/letsencrypt-cpanel#21]
Hi,

When I try to add a cert to a subdomain I get the following error.

Error occured: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: imap.pdrnet.biz, www.imap.pdrnet.biz, Type: urn:acme:error:unauthorized

I had no prblem adding to example.com and www.example.com.  Any suggestions?

Thanks for a great plugin.

**Comment by Prajithp** [comment]
are you sure the mentioned domain is pointing to the same server where you installed the plugin?

**Comment by cjbooth22** [comment]
Yes, the cPanel server has about 20 IP's and the IP associated with the PDRnet.biz domain (no point in masking the domain name for obvious reasons) is on the same cPanel server that I installed the plugin.
1.

**Comment by comeback01** [comment]
I have the same problem

**Comment by Prajithp** [comment]
Okay thanks, Will look into this and update you soon.

**Comment by Taubin** [comment]
I am having the same issue while attempting to install certs on my sites. I've done a bit of searching and have not been able to find a solution. If I'm able to provide any kind of logs or anything to assist, please let me know. 

Error occured: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: site.com, www.site.com, Type: urn:acme:error:unauthorized

**Comment by homotechsual** [comment]
We're also seeing this issue on a cPanel server with Multiple IPs.

**Comment by coolacid** [comment]
I think I found the issue. 

The plugin will NOT let you create SSL certs for domains that already have SSL certs. So, I deleted the existing ones. 

Of course, I had a .htaccess to redirect non-https traffic to https, and since the certs were gone, let's encrypt couldn't verify the certs. 

Once I removed these lines from .htaccess, I could create my certs with the plugin, and returned to auto-redirect after.

**Comment by Prajithp** [comment]
@coolacid Yes, you are right. If the domain has self signed certificate and if you set non-https traffic to https, let's encrypt failed to  verify the certs due SSL warning. Will update the README soon :)

**Comment by sathyavpk** [comment]
Any issue when using in a server where ndeploy installed? 
I am getting the error when trying to install ssl certs for the whm services

Error occurred: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: lx.XXXX.com, Type: urn:acme:error:unauthorized

CENTOS 7.2 x86_64 standard – lx  WHM 56.0 (build 18)

**Comment by sathyavpk** [comment]
I got it solved by reinstalling the ndeploy script after installation of letsencrypt plugin and it worked fine.

Thank you
