### ISSUE TITLE
Install LetsEncrypt client separately?

### ISSUE THREAD

**Issue by MWDelaney** [Prajithp/letsencrypt-cpanel#23]
I apologize for asking an extremely basic question, but I need to write up a plan for potentially implementing this plugin on our servers and want to be sure to include everything. 

Does the plugin installer also install the LetsEncrypt application, or is that required to be installed separately?

Thanks!

**Comment by will-ashworth** [comment]
@MWDelaney Do you mean the LetsEncrypt "client"? (the library that this plugin uses)

If that's what you're asking...then yes. I believe it does. It should install dependencies needed in order to run the plugin on your server(s).

**Comment by MWDelaney** [comment]
I'm sorry, yes, I meant the client. Thank you!
