### ISSUE TITLE
Latest merge issue

### ISSUE THREAD

**Issue by BeZazz** [Prajithp/letsencrypt-cpanel#24]
I just updated and there is an issue

CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Prajithp** [comment]
Where did you see this error? also, please let me know how to recreate the
same.

**Comment by BeZazz** [comment]
Running git pull fails on all servers I have tried on.

Nothing I do seems to work git pull is choking on the README.md

Auto-merging README.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by Prajithp** [comment]
Can you do one thing, please delete the letsencrypt-cpanel directory and re-clone it?

**Comment by BeZazz** [comment]
Yep that worked. (Just deleting the file didn't as I tried before.)

So the fix is to delete the letsencrypt-cpanel directory on all servers?

**Comment by Prajithp** [comment]
yes, you should delete letsencrypt-cpanel dir on all servers to fix this :(

**Comment by BeZazz** [comment]
Ok thanks :)
