### ISSUE TITLE
Works from WHM, does not work from cPanel. No log file.

### ISSUE THREAD

**Issue by mwdelaneytwg** [Prajithp/letsencrypt-cpanel#25]
Hello!
This tool is great! Thank you so much for building this!

I'm having some trouble making it work from cpanel. I'm able to install certificates from WHM with no difficulty, but when I try to install from cpanel I get the following:

```
Something went wrong, kindly check the letsencrypt log file
```

But there is no log file in /var/letsencrypt

Any insight on how I can investigate this issue? 

It's perhaps noteworthy that the site I'm attempting to install a cert for does NOT have a dedicated IP. Again, despite this, everything works fine from WHM but not from cPanel.

Thanks for any help you can provide!

**Comment by BeZazz** [comment]
Was this a subomain created as its own  account in WHM?

**Comment by Prajithp** [comment]
Could you please contact me on prajithpalakkuda@gmail.com? as I need some more details on this.
