### ISSUE TITLE
subdomain, Error occured: Status: 403, solution !

### ISSUE THREAD

**Issue by comeback01** [Prajithp/letsencrypt-cpanel#27]
Sometimes with a subdomain I have this error:

Error occured: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: xxx.yyy.com, Type: urn:acme:error:unauthorized

I found the following solution:

For example, the domain name is abc.com

My subdomain is 123.abc.com

I put in the DNS, www.123.abec.com

And it works.

**Comment by Prajithp** [comment]
@comeback01 Thank you so much. Will fix this by end of this week and update you.

**Comment by Prajithp** [comment]
Could you please update your installation and see if this has fixed or not? I could not re-create this issue.
