### ISSUE TITLE
Two cron entries

### ISSUE THREAD

**Issue by BeZazz** [Prajithp/letsencrypt-cpanel#28]
Just noticed this at the bottom of all the root crons I checked.
Also note extra space between \* and /

00 00 \* \* \* /scripts/renew_letsencrypt_ssl.pl > /dev/null 2>&1
00 00 \* \* \*  /scripts/renew_letsencrypt_ssl.pl > /dev/null 2>&1

**Comment by Prajithp** [comment]
You can remove the duplicate cron entry manually as this has already fixed in the last commit.
