### ISSUE TITLE
Should .well-known/acme-challenge be removed?

### ISSUE THREAD

**Issue by setroot** [Prajithp/letsencrypt-cpanel#29]
I noticed the folder .well-known/acme-challenge

After doing more research on it, this is what I found.

https://github.com/letsencrypt/letsencrypt/issues/2049
https://github.com/letsencrypt/letsencrypt/issues/1003

On the second link

> >  kuba commented on Oct 16, 2015
> >  cleanup() should delete .well-known/acme-challenge when all previously perfomed challenges have been cleaned up. This requires us to track the status of all incoming challenges, just like standalone2 does.

**Comment by BeZazz** [comment]
Both those links 404 for me.

**Comment by setroot** [comment]
@BeZazz I have fixed the links. I don't think this will fix the issue that you brought on https://github.com/Prajithp/letsencrypt-cpanel/issues/26

**Comment by Prajithp** [comment]
@whosjose Yes, the hidden dir should be removed  afterwards. I will work on this and update here once it is fixed.

**Comment by ian81** [comment]
Still present based on fresh install on May 11, 2016.

**Comment by setroot** [comment]
@ian81 Yes, there hasn't been an update as of yet. Once an update kicks in the issue would be closed.

**Comment by Prajithp** [comment]
I have merged this feature into the main branch, please check it out and let me know. Will close this issue after that.

 Thanks :)

**Comment by ian81** [comment]
Updated the script. Tested on a couple of domains. Seems to remove the files after the cert is installed.

**Comment by Prajithp** [comment]
@ian81 Thank you for the confirmation.
