### ISSUE TITLE
ACME;pm Error When Trying To Install On WHM services

### ISSUE THREAD

**Issue by varanasib** [Prajithp/letsencrypt-cpanel#33]
Whether I try to install on one of the items listed or several, the plugin reports this error:

`Not an ARRAY reference at /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5/Protocol/ACME.pm line 713.`

BTW, I love your plugin.  Thanks very much!

**Comment by Prajithp** [comment]
@varanasib Which version of cPanel are you using? Please let me know asap.

**Comment by varanasib** [comment]
I'm on version 54.0.21

Oops, 54.0.22

**Comment by Prajithp** [comment]
Make sure your server hostname is setup properly. I could not able to recreate this issue in any of our cPanel server.

**Comment by ivspassov** [comment]
Not an ARRAY reference at /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5/Protocol/ACME.pm line 718.
