### ISSUE TITLE
Logo isn't appearing in cPanel

### ISSUE THREAD

**Issue by xmovu** [Prajithp/letsencrypt-cpanel#35]
Hi folks,

The LetsEncrypt logo isn't appearing in cPanel/WHM.

It tries to load: 

https://srv1.testserver.com:2083/cpsess151211/3rdparty/letsencrypt-cpanel-ui/img/icon.png

Any idea?

Template: paper_lantern
WHM 54.0 (build 22)

**Comment by ghesi** [comment]
Hi,

I have installed today the script and I can confirm that cpanel icon is missing.

**Comment by Prajithp** [comment]
@mrgeneral @ghesi, cPanel icon is loading fine for me. Could you please reinstall this plugin? and see if it is loading or not?

**Comment by xmovu** [comment]
Hello,

Solved, thank you very much for the help and for the great plugin. It is excellent!

**Comment by Prajithp** [comment]
@mrgeneral :+1:

**Comment by Prajithp** [comment]
@mrgeneral :+1:
