### ISSUE TITLE
Renew script not working

### ISSUE THREAD

**Issue by adminko-svk** [Prajithp/letsencrypt-cpanel#37]
Hi,
I have in crontab:
`00 00 * * *  /scripts/renew_letsencrypt_ssl.pl > /dev/null 2>&1`

But it is not working, in WHM I have domains with expired Let's Encrypt certificates.
Where is the problem? How can I renew it?

**Comment by Prajithp** [comment]
I have checked this and confirmed renewal script is working fine. Could you please provide log file /var/letsencrypt/letsencrypt.log?

**Comment by adminko-svk** [comment]
I have there 30x the same error:

`Failed to renew SSL certificate for hostname : Died at /usr/local/cpanel/Cpanel/LetsEncrypt/Service.pm line 147.`

**Comment by Prajithp** [comment]
@adminko-svk This has been fixed in the last commit.

**Comment by LanceSandino** [comment]
Can't locate Cpanel/LetsEncrypt.pm in @INC (@INC contains: /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /scripts/renew_letsencrypt_ssl.pl line 8.
BEGIN failed--compilation aborted at /scripts/renew_letsencrypt_ssl.pl line 8.

**Comment by Prajithp** [comment]
A re-installation would fix this issue. Please let me know if you are still facing the same problem even after the reinstall.
