### ISSUE TITLE
Update domain owner email id on subdomains

### ISSUE THREAD

**Issue by ghost** [Prajithp/letsencrypt-cpanel#38]
When i try to set up an SSL cert for a subdomain, sub.mydomain.com (for example), it says to me "Update the domain owner email id in whm first".
So i went into WHM to the account list and set the user email (the user who was the owner of the domain and the subdomain), but even after setting it, it still gives me the same error. There are no redirects active on the website.
After a few tries i managed to create a certificate for the main domain (at first it gave me "Authorizations for these names not found or expired: sub.mydomain.com, Type: urn:acme:error:unauthorized"), but it still not work with the subdomain

**Comment by Prajithp** [comment]
This has been fixed on last commit.
