### ISSUE TITLE
Upgrade Instructions in README Don't Work-Remove, Install Does

### ISSUE THREAD

**Issue by varanasib** [Prajithp/letsencrypt-cpanel#39]
The instructions on how to upgrade in README don't work.  Following them for the last upgrade results in errors like those in #10.  (@INC path errors for Protocol::ACME and cpanel reporting "No response from subprocess" etc.)  The plugin doesn't use the system's Protocol::ACME, I guess.

Uninstalling and installing again per the README worked fine.

Again, this is a great plugin.  Thanks so much.

**Comment by Prajithp** [comment]
Thank you so much for the bug report :)

 This has been fixed now.
