### ISSUE TITLE
Installed the Plugin but SSL Install takes forever

### ISSUE THREAD

**Issue by ManoSmriti** [Prajithp/letsencrypt-cpanel#4]
I have installed the plugin. but for some reason the same happened on two of our servers.
the SSL install takes for ever. and SSL is not installed.both have WHM build 8.

**Comment by Prajithp** [comment]
Could you please provide more info about this? Also, please send me the following log files for further troubleshooting.

 /usr/local/cpanel/logs/error_log
/var/log/letsencrypt/letsencrypt.log
