### ISSUE TITLE
cpanel plugin window not working

### ISSUE THREAD

**Issue by ghost** [Prajithp/letsencrypt-cpanel#42]
While trying to solve [this](https://github.com/Prajithp/letsencrypt-cpanel/issues/41) problem, I tried for the first time to enter the cpanel plugin interface (up until now I was doing everything on the WHM page), but it downloaded the index.live.pl file rather than open it.
I thought it was useful to say it, probably it was just an oversight...
My Cpanel doesn't have a valid SSL cert, or at least it has a self-signed, since it's always giving me the barred lock and the "unsecure" page. I don't know if this is related, but maybe it could be useful :)

**Comment by BeZazz** [comment]
Sounds like your server is setup incorrectly .i.e. Not setup to run pearl files.

**Comment by ghost** [comment]
Hi, thank you for your immediate answer, I'm not the one who installed cpanel on that machine, but i guess you're probably right. Do you know how it should be setted up? Looking on the net i saw some pages that were talking about installing pearl modules under Cpanel->Software->Pearl module , however i don't really know what to look for. The current user doesn't have any specific perl module installed, just the system modules...
Do you know how to set it up correctly? Or some website with informations about it?
Thank you!

**Comment by BeZazz** [comment]
Start with error logs
https://documentation.cpanel.net/display/ALD/Perl+Module+Installation#PerlModuleInstallation-Errorlogs

**Comment by ghost** [comment]
Ok, mine it's about 2200 rows long, but i hadn't seen anything like `Can't locate DB_File.pm in @INC`, which was listed in the link you sent...

**Comment by Prajithp** [comment]
@AndreaDrago96 cPanel installation seems to be broken in your case. So could you please run upcp with force argument? and let me know.

**Comment by ghost** [comment]
upcp is the update script, right? I'm a little worried because there are different active costumer websites, so I can't afford to turn them down. Moreover, every other component in both whm or cpanel work prefectly, so it seems a little strange that the installation is broken...

**Comment by Prajithp** [comment]
Nothing will happen if you run upcp, don't worry about that. Normally this can happen if cpanel cgi doesn't work properly, so please let me know if you need any further help for fixing this issue. You can contact me on prajithpalakkuda@gmail.com.
