### ISSUE TITLE
32x32 icon for x3/retro theme

### ISSUE THREAD

**Issue by hbouma** [Prajithp/letsencrypt-cpanel#45]
Hi,

Is there any chance we could have a 32x32 icon done for the x3 and retro themed skins? Or for rvskin and third party skins as well... For some reason the 48x48 icon doesn't show up in the security section (and looks out of place if its there) when using the depreciated theme or the retro style.

Thanks. Your plugin is really nice btw.

Hal

**Comment by Prajithp** [comment]
@hbouma Would you able to create one icon for this? Otherwise, I will work on this weekend.

**Comment by itseasy21** [comment]
32x32 icon here : [http://i.imgur.com/uxzLutN.png](http://i.imgur.com/uxzLutN.png)

**Comment by Prajithp** [comment]
Added  32x32 icon for x3.retro theme.

**Comment by hbouma** [comment]
Awesome. Thanks for your help!
