### ISSUE TITLE
Auto redirection not working

### ISSUE THREAD

**Issue by box-as** [Prajithp/letsencrypt-cpanel#46]
Hi Prajith,
]
Hope you are doing great! I tried using this plugin at my end but found that the domain name does not automatically redirect to https protocol. While if I type https://example.com then it works but if I type http://example.com it stays to non secure url without https. I tried adding manual redirection from cpanel and .htaccess but that didn't worked either, the webpage stops working showing too many redirections for the page. 
Can you please provide me possible solution on this?

Thanks,
Saurabh

**Comment by Prajithp** [comment]
This has to be done from your end. Letsencrypt doesn't setup any kind of redirection in your htaccess file. Please check your web application settings and configure your htaccess accordingly.
