### ISSUE TITLE
WHM Services certificate is issued even if it has a valid certificate and is re-issued daily 

### ISSUE THREAD

**Issue by gpant** [Prajithp/letsencrypt-cpanel#47]
The Services certificate is forcefully issued even though a certificate is already used, in our case our certificate is getting replaced by the lets encrypt certificate every time. Since we didnt want to change it back everytime we decided to let it use the lets encrypt certificate. But now on each cron run it issues a new certificate for the services.

**Comment by Prajithp** [comment]
This has been fixed in the last merge. Please check it out and let me know.
