### ISSUE TITLE
How do I enable ssl for email? Add mail.domain.com to cert?

### ISSUE THREAD

**Issue by Blindmikey** [Prajithp/letsencrypt-cpanel#49]
First, thank you for this wonderful plugin. I came from the beta command line interface from letsencrypt, and while that worked for me on my own home server, setting up the same on a centOS RHEL box with heavy integration with cPanel/WHM was not an ideal solution. 

Finding this cpanel plugin was a life saver - thank you!

There are a few last pieces I'm attempting to rectify, one of which is enabling ssl for mail handled by our server. How would I go about adding mail.domain.com to the certificate? 

Thank you!

**Comment by Prajithp** [comment]
You have to create mail.domain.com subdomain first and then you can generate cert for the same using letsencrypt plugin.
