### ISSUE TITLE
Domain sorting

### ISSUE THREAD

**Issue by adminko-svk** [Prajithp/letsencrypt-cpanel#5]
Hello,
your script works excellent, thank you very much!

But can you sort the table and the select form alphabetically?
And how can I run the renew script from CRON?

Thank you!

**Comment by Prajithp** [comment]
working on this feature :)

**Comment by Prajithp** [comment]
@adminko-svk 

   mentioned feature is now merged into active branch, please uninstall the current version by using the following command.

``` 
  rm -rvf /usr/local/cpanel/Cpanel/LetsEncrypt.pm
  rm -rvf /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl
  rm -rvf /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/index.tt
  rm -rvf /usr/local/cpanel/whostmgr/docroot/addon_plugins/ico-letsencrypt.svg
  /usr/local/cpanel/bin/unregister_appconfig LetsEncrypt
```

Also, please note that, in this version I have removed python dependency, so please let me know if you get any errors while installing ssl certs.

**Comment by adminko-svk** [comment]
Thank you, but after uninstalling and installing a have a problem:

```
Internal Server Error
500
No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.
```

**Comment by Prajithp** [comment]
Could you please send the log file /usr/local/cpanel/logs/error_log to prajithpalakkuda@gmail.com? so that I can check and fix the issue.

**Comment by adminko-svk** [comment]
you have mail

**Comment by Prajithp** [comment]
Found the issue. Can you please install JSON::XS module?

```
 /scripts/perlinstaller JSON::XS
```

**Comment by adminko-svk** [comment]
`CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.
JSON::XS is missing the no_set_utf8 flag at /usr/local/cpanel/Cpanel/JSON.pm line 151.
Can't call method "whm_api" on an undefined value at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 164.
[2016-02-11 10:48:39 +0100] info [cpsrvd] Internal Server Error: "GET /cpsess1127326382/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.

**Comment by Prajithp** [comment]
are you still getting the same error even after installing that above mentioned module?

perl -MJSON::XS -e1 

can you run that command for me?

**Comment by adminko-svk** [comment]
Last error:
`CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.
JSON::XS is missing the no_set_utf8 flag at /usr/local/cpanel/Cpanel/JSON.pm line 151.
Can't call method "whm_api" on an undefined value at /usr/local/cpanel/Cpanel/LetsEncrypt/WHM.pm line 164.
[2016-02-11 10:59:56 +0100] info [cpsrvd] Internal Server Error: "GET /cpsess1127326382/cgi/letsencrypt/letsencrypt.pl HTTP/1.1" 500 No response from subprocess (/usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl): The subprocess reported error number 2 when it ended.
`

```
root@ws1 [~/letsencrypt-cpanel]# perl -MJSON::XS -e1
root@ws1 [~/letsencrypt-cpanel]#
```

**Comment by Prajithp** [comment]
my mistake :(,

   install this as well. 
       /scripts/perlinstaller cPanel::PublicAPI

**Comment by adminko-svk** [comment]
Great, it works!

For info - list of today installed PERL modules:
Protocol::ACME
JSON::XS
Mozilla::CA
CGI
cPanel::PublicAPI

Thank you!

**Comment by Prajithp** [comment]
Cool :) Thank you for sharing the modules list

**Comment by adminko-svk** [comment]
Now I **can not create SSL certs**...
After installing via WHM, the Provider value in table is blank.
Also the new cert is only 2048bit (and not working).

Error log:

```
CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.
JSON::XS is missing the no_set_utf8 flag at /usr/local/cpanel/Cpanel/JSON.pm line 151.
CGI::param called in list context from /usr/local/cpanel/whostmgr/docroot/cgi/letsencrypt/letsencrypt.pl line 36, this can lead to vulnerabilities. See the warning in "Fetching the value or values of a single named parameter" at /usr/local/share/perl5/CGI.pm line 405.
```

**Comment by Prajithp** [comment]
Not sure what could be the issue. Can you remove the existing one and install it again? as I was able install ssl certs without any issues.

**Comment by adminko-svk** [comment]
the problem persists...

**Comment by adminko-svk** [comment]
Works! 
After complete uninstalling and installing again.

Thank you!
