### ISSUE TITLE
Not an ARRAY reference at /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5/Protocol/ACME.pm line 718.

### ISSUE THREAD

**Issue by ivspassov** [Prajithp/letsencrypt-cpanel#51]
I'm getting this error , after trying to install certificate:
Not an ARRAY reference at /usr/local/cpanel/base/3rdparty/letsencrypt-cpanel-ui/lib/perl5/Protocol/ACME.pm line 718.

**Comment by Prajithp** [comment]
Not sure what could be the issue. Could you please reinstall and see if the issue is still persist.

**Comment by ivspassov** [comment]
Funny thing is , that it worked for one domain name , and it wont work for another...
