### ISSUE TITLE
Hi plugin problem on CPanel

### ISSUE THREAD

**Issue by FreddyFoxxx** [Prajithp/letsencrypt-cpanel#52]
Hi to all thanks very much for the plugin and work ..

I have this problem let me every day certifies the SMTP mail certificate dovecot etc .. on this cron I found this:

  00 00 \* \* \* /scripts/renew_letsencrypt_ssl.pl> / dev / null 2> & 1

to not have every day the renewal ??

**Comment by Prajithp** [comment]
Please update to latest version. That would fix your issue.
