### ISSUE TITLE
No Option to Install SSL ( Alias )

### ISSUE THREAD

**Issue by itseasy21** [Prajithp/letsencrypt-cpanel#53]
I am getting no option to install SSL on the parked domains.

**Comment by Prajithp** [comment]
Just install the cert for main domain, that will enable cert for parked domains as well.

**Comment by benjamin-smith** [comment]
For anyone stumbling in from Google, the docs also state,

> The second section will list all of the domains configured in your account that are eligible to have a certificate issued for. Please note, redirected domains are unable to have a certificate issued.

Check out the alias/addon domains page in cPanel and see what the value is for "Redirects to". cPanel attempts to derive if a redirect is in place by parsing the `.htaccess` file, but it doesn't work well. Edit the `.htaccess` file to ensure that value is "not redirected", then your domains should appear on the Let's Encrypt screen.
