### ISSUE TITLE
Protocol::ACME is NOT installed

### ISSUE THREAD

**Issue by joshkraemer** [Prajithp/letsencrypt-cpanel#58]
I'm trying to install the plugin, but I get the following message which halts the installation process. I do what the plugin suggests (install using /scripts/perlinstaller - appears to be successful), but I still don't see anything under the plugins section in cPanel WHM. From what I can tell, I believe this error could be related to the fact that I am on an older version of Centos (CENTOS 5.11 i686 virtuozzo – host  WHM 56.0 (build 22)).

```
Protocol::ACME is NOT installed
Installing Protocol::ACME
.....
.....
 Testing  perl modules we just installedw
.....
Protocol::ACME is NOT installed
.....
There was an error verifying  required perl modules are installed.
The following perl modules could not be installed:
Protocol::ACME
You can try installing these modules by running
/scripts/perlinstaller <module_name>
for each module name listed above.
```

**Comment by Kateicon** [comment]
Glad to see I'm not alone.

I'm also on older Centos, so you might be on to something there.

**Comment by itseasy21** [comment]
Have you tried running  
`/scripts/perlinstaller Protocol::ACME`

**Comment by Kateicon** [comment]
Yes.

Get Outlook for Androidhttps://aka.ms/ghei36

On Fri, Jun 17, 2016 at 12:38 AM +1000, "Shubham Mathur" <notifications@github.com<mailto:notifications@github.com>> wrote:

Have you tried running

/scripts/perlinstaller Protocol::ACME

##

**Comment by Prajithp** [comment]
@itseasy21 Thank you so much for helping out him.

**Comment by SdupuisBlax** [comment]
@Prajithp why has the issue been closed when there have been no fixes posted..., @itseasy21 suggested running the perlinstaller but the original issue description shows he tried that (and so have I) and it doesn't work!

Here is output from pearlinstaller and install.sh :

```
Mirror Check passed for cpan.mirror.rafal.ca (/index.html)
Searching on cpanmetadb ...
Searching Protocol::ACME on cpanmetadb (http://cpanmetadb.cpanel.net/v1.0/package/Protocol::ACME) ...
Source: fastest CPAN mirror ... Protocol::ACME is up to date. (0.12)
root@smart2 [~/letsencrypt-cpanel]# ./install.sh
Protocol::ACME is NOT installed
Installing Protocol::ACME
.....
.....
 Testing  perl modules we just installed
.....
Protocol::ACME is NOT installed
.....
There was an error verifying  required perl modules are installed.
The following perl modules could not be installed:
Protocol::ACME
You can try installing these modules by running
/scripts/perlinstaller <module_name>
for each module name listed above.
```

**Comment by will-ashworth** [comment]
Couple of things that come to mind:
- Ensure host name is set correctly
- CentOS 5 doesn't support SNI, so you're going to run into issues if you don't have static IP addresses for everything
- Ensure you are not using 2FA for root (it may work at this time, but I recall there being an issue at one point)

Hope this helps someone.

**Comment by SdupuisBlax** [comment]
So the actual issue is that let's encrypt can't be supported properly on WHM/cPanel on CentOs 5? **That should be specified somewhere, perhaps on the README.MD**. 

I know CentOS 5 is on EOL for WHM/cPanel support but a lot of servers are still running on it.

**Comment by will-ashworth** [comment]
I didn't say "not supported". I did say you'd need static IP addresses on everything. One of the big reasons a lot of people abandoned CentOS 5 years ago in favor of 6, is that SNI was supported. This meant less static IPs needed.

It is stated in the previous issues (I'm the one that mentioned it a few months ago), but you're welcome to contribute to the README if you like.

Are you fully updated with yum and cPanel on your CentOS 5 server?

Also, depending on when you installed, it may be worth it to remove (not upgrade) and completely re-add this script...then reinstall it. Curious if that fixes the issue for you.

**Comment by SdupuisBlax** [comment]
It's fine for me, i'll just update the server to newer OS, it was on our TODO list anyway before fall 2016 so this is a good reason to push forward. Although, to answer, yes I keep an updated server aside from still rolling on CentOS 5. I don't have enough static IPs for my needs also.

Perhaps it is supported but it requires a few workarounds and defeats the purpose of actually using let's encrypt which is auto renewal and maintenance. The fact that I am here discussing this issue shows that it's not clear enough on the get go that there are issues with Let's encrypt plugin and CentOS 5.

Thanks for the quick replies though
