### ISSUE TITLE
Not detecting Protocol::ACME

### ISSUE THREAD

**Issue by Kateicon** [Prajithp/letsencrypt-cpanel#59]
ran the install.sh, didnt find Protocol::ACME installed, tried to install it and failed. 

installed it manually via the provided command - /scripts/perlinstaller Protocol::ACME

this ran through and installed it with no problems, but the install.sh still can't find it.

Protocol::ACME is NOT installed
Installing Protocol::ACME
.....
.....
 Testing  perl modules we just installed`
.....
Protocol::ACME is NOT installed
.....
There was an error verifying  required perl modules are installed.
The following perl modules could not be installed:
Protocol::ACME
You can try installing these modules by running
/scripts/perlinstaller <module_name>
for each module name listed above.

**Comment by Kateicon** [comment]
woops, dupe of https://github.com/Prajithp/letsencrypt-cpanel/issues/58

**Comment by Prajithp** [comment]
Please install the module using  command "/scripts/perlinstaller   Protocol::ACME" and let me know

**Comment by Kateicon** [comment]
As I said in my original post **I ALREADY TRIED THAT**.

**Comment by will-ashworth** [comment]
@Kateicon 

And as @Prajithp said in his post "please" and "let me know".

Other things you can try:
- including a copy of your logs pertinent to this issue
- ensuring that what the script is looking for is, in fact, in your "path"
- closing your terminal window, and re-opening it (essentially re-sourcing your path variables after install)
- contributing to development (it's open source, after all)

No need to be rude in your responses. Please remember that this plugin is free, and you haven't paid anything for it. He's put a great deal of effort into this solution where others have not. If it's not what you're looking for, you're welcome to look elsewhere. We won't stop you.

> _You catch more flies with honey than you do with vinegar._

**Comment by Kateicon** [comment]
I did let him know, in my original post.
