### ISSUE TITLE
[FIXIT] We  get always are error

### ISSUE THREAD

**Issue by dochardi** [Prajithp/letsencrypt-cpanel#6]
Hello We get That error

> Updating letsencrypt and virtual environment dependencies......Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt certonly --config /tmp/GAMD0Q3FJ3.conf --renew-by-defaultVersion: 1.1-20080819Version: 1.1-20080819Failed authorization procedure. bewo.dwe-gruppe.eu (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://bewo.dwe-gruppe.eu/.well-known/acme-challenge/IDIx4VlfaTLoT6_TGpsRBYQSMfB9ijr_d286dbYfhg8, www.bewo.dwe-gruppe.eu (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Could not connect to http://www.bewo.dwe-gruppe.eu/.well-known/acme-challenge/kjSXLcHp-ZUqJwK5d0EsY2NILNjm3TFLfXHtrWBGHEsIMPORTANT NOTES: - The following errors were reported by the server: Domain: bewo.dwe-gruppe.eu Type: urn:acme:error:connection Detail: Could not connect to http://bewo.dwe-gruppe.eu/.well-known /acme-challenge/IDIx4VlfaTLoT6_TGpsRBYQSMfB9ijr_d286dbYfhg8 Domain: www.bewo.dwe-gruppe.eu Type: urn:acme:error:connection Detail: Could not connect to http://www.bewo.dwe-gruppe.eu/.well- known/acme-challenge/kjSXLcHp-ZUqJwK5d0EsY2NILNjm3TFLfXHtrWBGHEs

And yes we are login to whm as root and what we see are that he not set the acme-challenge files

kai

**Comment by Prajithp** [comment]
Are you sure the domain http://bewo.dwe-gruppe.eu/.well-known is pointing to the same server?

**Comment by dochardi** [comment]
yes i am sure

**Comment by dochardi** [comment]
For you information and maby you add this to the readme you need to dissable cPanel/Bluehost’s EasyApache Symlink patch

**Comment by Prajithp** [comment]
Thanks for the fix, please open a pull request if it possible
