### ISSUE TITLE
Authorizations for these names not found or expired

### ISSUE THREAD

**Issue by will-ashworth** [Prajithp/letsencrypt-cpanel#62]
I have `ads.mydomain.com` added as a cPanel account (subdomain added as a separate cPanel account), and when attempting to register SSL for it, I'm greeted with the following message. Any ideas?

```
Error occurred: Status: 403, Detail: Error creating new cert :: Authorizations for these names not found or expired: www.ads.mydomain.com, Type: urn:acme:error:unauthorized
```

We don't use `www.ads.mydomain.com`, but the LE plugin is attempting to test on the `www` version of the domain. Any help you can offer is appreciated. Thanks!

**Comment by will-ashworth** [comment]
I'll note that creating another DNS entry so that `www.ads.mydomain.com` resolves to `ads.mydomain.com` resolved the issue. Because the verification should work then.

But still, we shouldn't need to create unused DNS records. The system should know if we're using `www.` or not   ;-)

**Comment by ivanhosgood** [comment]
Will, thanks for posting the resolution to this issue, been scratching my head with this one

**Comment by webspes** [comment]
Please let us know when this is fixed in the source code. I downloaded/installed code today (upgrade) and that didn't help.

**Comment by will-ashworth** [comment]
@pmax1 Try uninstalling, then immediately reinstalling. That may resolve your issue.

@ivanhosgood No problem! Glad it helped someone.

**Comment by Prajithp** [comment]
@will-ashworth Thanks you so much for the fix. I was really busy with my other projects  and some other family issues. 

Also, I'm planing to add an option to select domains instead of adding aliases blindly. Will update you, when it is available for testing.

**Comment by gvibrations** [comment]
@will-ashworth Which way did you create another DNS entry? I've been pulling my hair out on this one. I just uninstalled and reinstalled the code ... but I still can't create the cert.

Should note that I'm doing this on a server with a WP Multisite running ... can't create the cert on an addon domain.

**Comment by will-ashworth** [comment]
Hey @timcaviness 

I went into DNS where DNS is managed for that domain name (in my case, Cloudflare); then I added the `www` CNAME to `mydomain.com`. Then I re-tried creating the cert. It worked because DNS for that domain was available for ACME to successfully "validate" the domain name.

Right now, this plugin for certificates attempts to secure the `www` version of the domain as well. Normally there isn't an issue with this, except in my case I had a subdomain added as its own cPanel account. And really...why would I have a `www.subdomain.mydomain.com`? I only wanted a cert for `subdomain.mydomain.com`.

But to answer your question, creating `www.subdomain.mydomain.com` in DNS to resolve to the server in question; that was the key to getting the certificate working successfully. Because only then could ACME complete its verification.

**Comment by gvibrations** [comment]
That did it!

I'm using Cloudflare for both the domain.com and the subdomain.com ... 

I went to the domain.com site in cloudflare, created a CNAME for `www.subdomain` that pointed to `domain.com` and the plugin worked like normal.

Kudos.

**Comment by webspes** [comment]
"Try uninstalling, then immediately reinstalling. That may resolve your issue."

It is only a problem for sub-domains like the other people here is commenting. It works for normal domains. I assume this isn't fixed in the code just now?

**Comment by will-ashworth** [comment]
Great @timcaviness Glad you were able to get it working  :)

**Comment by will-ashworth** [comment]
@pmax1 

@Prajithp posted earlier today that it's on his radar to fix this at the code level. Creating the DNS entry is merely a workaround solution in the interim.
