### ISSUE TITLE
Permission denied on Cpanel and loop loading on WHM

### ISSUE THREAD

**Issue by AlsonicTech** [Prajithp/letsencrypt-cpanel#63]
First issue is that when I try accesing Let`s encrypt plugin from WHM it goes in an infinite loop loading.
Second issue is that when I try adding the certificate from cPanel I get this error message:

> mkdir /home/FOO/public_html/.well-known/acme-challenge: Permission denied at /usr/local/cpanel/Cpanel/LetsEncrypt/Challenge.pm line 73.

**Comment by Prajithp** [comment]
Please make sure that root user has rights to create directory's in  public_html folder.
