### ISSUE TITLE
AH00548: NameVirtualHost has no effect and will be removed in the next release /usr/local/apache/conf/httpd.conf:307

### ISSUE THREAD

**Issue by locusluxlucis** [Prajithp/letsencrypt-cpanel#64]
Critical error with httpd once an SSL is installed on a domain.  Fresh clean WHM install. No other modules installed. Centos w/ WHM V56.0 Build 22

**Comment by locusluxlucis** [comment]
Fresh clean WHM install. No other modules installed.

**Comment by Prajithp** [comment]
You can ignore that massage as it is normal.
