### ISSUE TITLE
CRON problem

### ISSUE THREAD

**Issue by adminko-svk** [Prajithp/letsencrypt-cpanel#7]
This is output from CRON job `/scripts/renew_letsencrypt_ssl.pl`:

`CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.`

**Comment by hedqvist** [comment]
I also recive this in the daily cron mails.
Subject: Cron root@vps1 /scripts/renew_letsencrypt_ssl.pl
Message: CDB_File could not be loaded. You may see pages in English rather than in your desired locale at /usr/local/cpanel/Cpanel/Locale/Utils.pm line 11.

**Comment by Prajithp** [comment]
This is a warning and you can simply ignore it. Will release a patch to fix
this issue soon.

**Comment by Prajithp** [comment]
This has been fixed. Now all erros and messages are redirected to  /dev/null
