### ISSUE TITLE
error language

### ISSUE THREAD

**Issue by FreddyFoxxx** [Prajithp/letsencrypt-cpanel#78]
hello!

error report language fix italian  

`SCREEN:   http://prntscr.com/c31jlv`

congratulations you are doing a great job I congratulate you ... thanks to you and your efforts we have this form.

going to help with the donation as soon as possible!

I have only one request and feasible to put a elimna ssl client-side?

Best Regards!
Freddy

**Comment by Prajithp** [comment]
This has been fixed and merged into the master branch. Thank you @k-poole

**Comment by k-poole** [comment]
Oh I didn't even see this issue when I checked previously. Not a problem. cPanel also internally have created bug CPANEL-7890 to resolve this properly, but at least now it works again.

@FreddyFoxxx, just go to your git clone and run `git pull && ./upgrade.sh` your issue should be fixed.

Cheers

**Comment by FreddyFoxxx** [comment]
many thanks to all for the great fix job!
