### ISSUE TITLE
Issue with www

### ISSUE THREAD

**Issue by hostfusion** [Prajithp/letsencrypt-cpanel#87]
Hello,

from last update the plugin only install the certificate on https://domain.com not https://www.domain.com not include the www for certificate. Are this ok ? or have missing something ? Are There any way to fix this issue ?

Regards

PS

**Comment by BeZazz** [comment]
The only way I can get it to work is by adding

RewriteRule ^.well-known(.*)$ - [L,NC]

to the top of the .htaccess file

**Comment by Prajithp** [comment]
@hostfusion Will check it and let you know,

**Comment by hostfusion** [comment]
@Prajithp Thanks, i note that this issue happen in the cPanels accounts when install the certificate, although selections in the dialog box the domain with www only installs for the domain without www,  but if you install from whm manager work fine, install for all with o without www, for this i think the issue is with the cPanel manager. I hope this help.

Regards

PS

**Comment by hostfusion** [comment]
Hi @Prajithp do you have news ? :)

Regards

PS

**Comment by Prajithp** [comment]
@hostfusion @BeZazz Can you please check this and let me know?

**Comment by hostfusion** [comment]
@Prajithp Thanks, my first test its ok :) Fixed #87

**Comment by Prajithp** [comment]
Thanks @hostfusion for the confirmation
