### ISSUE TITLE
Installing certificate for the cpanel main domain?

### ISSUE THREAD

**Issue by XGhozt** [Prajithp/letsencrypt-cpanel#97]
I read somewhere that it only works with cnames or subdomains, etc.. but not the main domain? I ran into an issue where I had two separate cpanel accounts for "domain.com" and one for "sub.domain.com" -- I wasn't able to install a cert for "sub.domain.com" because it was picking up "www.sub.domain.com" instead.

A weird work around that worked was, I just opened the developer tools on my browser and added the "sub.domain.com" to the <select> field and submitted it. It worked perfectly fine.

So why wasn't the domain listed there to begin with? Am I going to run into issues when it's up for renewal?

**Comment by will-ashworth** [comment]
That's correct, from what I've seen. The easiest thing you can do so that renewals are more likely to happen correctly...

Setup a CNAME record in DNS for `www.sub.domain.com`, and have it reference `sub.domain.com`. This way validation from LE's end can succeed.
